name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t sebacetorca/elegionapp:latest .

    - name: Push Docker image to Docker Hub
      run: docker push sebacetorca/elegionapp:latest

    - name: Redeploy to Azure
      run: |
        # Aquí debes agregar los comandos necesarios para redeployar en Azure
        # Por ejemplo, puedes utilizar Azure CLI para detener y volver a iniciar tus contenedores
